### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by gvillo** [josiahayres/storybook-addon-mantine#12]
Hi, it would be awesome to add react 19 support since it's stable and launched now. I am using Mantine and this is one of the deps that it's raising a warning because of peerDeps

**Comment by josiahayres** [comment]
It seems Storybook doesn't yet [support React 19](https://github.com/storybookjs/storybook/issues/29805).
I'll look at removing the peer dependency for react from this library as that's [been available since 7.6](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#addons-no-longer-need-a-peer-dependency-on-react)

**Comment by elie-laloum** [comment]
Hey,

I use storybook to expose stories from a react 19 ui library in a pnpm monorepo !
pnpm dosn't allow to mix react versions so I can't use addons for the moment.

Is there a workaround ?

**Comment by josiahayres** [comment]
I've released `storybook-addon-mantine@5.0.0` which works for react 19 projects
